// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5N_mWTiAgeZLcrb8Te7gy8FHjwQ0Agm8',
    appId: '1:947930355288:web:cf384c6c3c486cf9fedc2d',
    messagingSenderId: '947930355288',
    projectId: 'bookly-6db9d',
    authDomain: 'bookly-6db9d.firebaseapp.com',
    storageBucket: 'bookly-6db9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXLgl0xVxRjKO6BehYtzylMFV3NXBy-ZI',
    appId: '1:947930355288:android:c6e057b96ff72c38fedc2d',
    messagingSenderId: '947930355288',
    projectId: 'bookly-6db9d',
    storageBucket: 'bookly-6db9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsAJCZeHu5UumuL2xKh_-jxIZraMFdEZo',
    appId: '1:947930355288:ios:254c899eb1c3e1cffedc2d',
    messagingSenderId: '947930355288',
    projectId: 'bookly-6db9d',
    storageBucket: 'bookly-6db9d.firebasestorage.app',
    iosClientId: '947930355288-stqmlq46hvt2n221slvmb77up58nejkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookly12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsAJCZeHu5UumuL2xKh_-jxIZraMFdEZo',
    appId: '1:947930355288:ios:254c899eb1c3e1cffedc2d',
    messagingSenderId: '947930355288',
    projectId: 'bookly-6db9d',
    storageBucket: 'bookly-6db9d.firebasestorage.app',
    iosClientId: '947930355288-stqmlq46hvt2n221slvmb77up58nejkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookly12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5N_mWTiAgeZLcrb8Te7gy8FHjwQ0Agm8',
    appId: '1:947930355288:web:6ab3a37a4e1a5aa4fedc2d',
    messagingSenderId: '947930355288',
    projectId: 'bookly-6db9d',
    authDomain: 'bookly-6db9d.firebaseapp.com',
    storageBucket: 'bookly-6db9d.firebasestorage.app',
  );
}
